spring.application.name=product-api

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommerce_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=springuser
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

server.port=8080
app.jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_FOR_ECOMMERCE_PROJECT_123456789
app.jwt.expiration=86400000 
app.jwt.refresh-expiration-ms=604800000
cloudinary.cloud-name=doqxmxawd
cloudinary.api-key=158429476483575
cloudinary.api-secret=LsYVufQkiB6bV9a_SGBrtoFRgIo